# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='link_to_organization',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='location_city',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='location_country',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='long_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
