# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 08:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_auto_20171112_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='org_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_banner',
            field=models.FileField(default=None, upload_to=webapp.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='organization',
            name='user_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
