# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20171123_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=None, null=True, unique=True),
        ),
    ]
