# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20171205_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='offer_additional_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='offer_food_checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='offer_food_detail',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='offer_housing_checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='offer_housing_detail',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='offer_stipend_checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='offer_stipend_detail',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='offer_studio_checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='offer_studio_detail',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='offer_tools_checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='offer_tools_detail',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='offer_travel_checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='offer_travel_detail',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='require_class_checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='require_class_detail',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='require_date_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='require_end_date',
            field=models.DateField(blank=True, help_text='Latest date the residency can end', null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='require_hackathon_checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='require_hackathon_detail',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='require_language',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='require_maximum_stay',
            field=models.CharField(blank=True, help_text='Minimum required length of stay', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='require_mentoring_checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='require_mentoring_detail',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='require_minimum_stay',
            field=models.CharField(blank=True, help_text='Minimum required length of stay', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='require_other_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='require_presentation_checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='require_presentation_detail',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='require_start_date',
            field=models.DateField(blank=True, help_text='Earliest date the residency can start', null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='require_talk_checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='require_talk_detail',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='require_workshop_checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='require_workshop_detail',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
