# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-18 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20180217_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='moderator_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='moderator_approved',
            field=models.BooleanField(default=False),
        ),
    ]
