# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-18 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20180218_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='location_state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
